### ISSUE TITLE
OLLAMA_HOST fails silently if missing https

### ISSUE THREAD

**Issue by michaelneale** [block/goose#133]
my OLLAMA_HOST was missing http:// -- this would be a great actual error message -- you found a variable but it was malformed.

**Comment by michaelneale** [comment]
cc @codefromthecrypt

**Comment by codefromthecrypt** [comment]
cool, I can have goose do this one 😎

**Comment by michaelneale** [comment]
@codefromthecrypt yep trying that out here: https://github.com/michaelneale/goose/pull/3 - so far so good (if it works ok will bring the action over to here). Added the goose fix it action

**Comment by pforhan** [comment]
latest goose seems a bit more chatty at least, it didn't like my ollama host not having a trailing `/`

**Comment by codefromthecrypt** [comment]
@pforhan wanna check #147? now uses URL.join so more tolerant about trailing vs not

**Comment by pforhan** [comment]
do I just take a patch from this and apply to the local cached files?

**Comment by michaelneale** [comment]
@pforhan if you clone it from that PR - you can run it via `uv run goose session start` to see it? should have it it in next release hopefully
